# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM Publish Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependancies  
        run: npm ci

      - name: Compile Typescript
        run: npx tsc

      - name: Creating .npmrc file
        run: mv .npmrc-dev .npmrc
      
      - name: Publish Package
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
